-- BiomeVegetationSetValue("data/biome/coalmine.xml", "fungus_loose", "tree_probability", 1.0)
-- BiomeVegetationSetValue("data/biome/coalmine.xml", "fungus_loose", "is_visual", true)
-- BiomeVegetationSetValue("data/biome/coalmine.xml", "fungus_loose", "load_this_xml_instead",
--     "mods/azoth/files/items/food/potato_plant.xml")
-- print("AZOTH PLANTS APPENDED")
